(ns metrology.view.journal-panel-settings)

(def column-settings
  [[:id 50 nil]
   [:count 100 nil]
   [:counteragent 350 nil]
   [:mi_type 250 nil]
   [:serial_number 150 nil]
   [:manufacture_year 75 nil]
   [:registry_number 100 nil]
   [:methodology 100 nil]
   [:interval 30 nil]
   [:components 350 nil]
   [:channels 50 nil]
   [:reference_codes 100 nil]
   [:area 30 nil]
   [:verification_type 30 nil]
   [:protocol_number 50 nil]
   [:usability 30 nil]
   [:date 100 nil]
   [:sticker_number 30 nil]
   [:sign_mi 30 nil]
   [:sign_pass 30 nil]
   [:temperature 75 nil]
   [:humidity 75 nil]
   [:pressure 75 nil]
   [:voltage 75 nil]
   [:frequency 75 nil] 
   [:other 100 nil]
   [:factor_7 30 nil]
   [:factor_8 30 nil]
   [:schema 30 nil]
   [:level 30 nil]
   [:reference_registry 30 nil]
   [:scope 350 nil]
   [:send_protocol 30 nil]
   [:unusability 250 nil]
   [:calibration_base 30 nil]
   [:upload 25 nil]
   [:engineer 75 nil]
   [:comment 300 nil]])

(def toolbar-fields-settings
  '(["id" " id "]
   ["выгрузка" " upload "]
   ["дата" " date "]
   ["зав. №" " serial_number "]
   ["количество" " channels "]
   ["контрагент" " ca_short_name "]
   ["объем" " scope "]
   ["протокол" " protocol_number "]
   ["рег. №" " registry_number "]
   ["состав" " components "]
   ["счет" " count "]
   ["тип СИ" " mi_type "]))
